### ISSUE TITLE
Could you make a Chinese version of the cheat?

### ISSUE THREAD

**Issue by BuShouFan** [Z4ee/Pipsi-ZZZ-Releases#13]
I'm playing the Chinese version of ZZZ, I know this cheat is only for the global version, I have already recharged in the Chinese version, so can I trouble you to make a Chinese version of the cheat?💀

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.2.1
