### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by LONRRyy** [Z4ee/Pipsi-ZZZ-Releases#15]
When I use PPS to open the game, it appears to be normal. However, after entering the game, pressing the hotkey Insert does not work. I tried resetting the hotkey to another key in the settings.ini file, but pressing the new hotkey in the game still has no effect.

**Comment by LONRRyy** [comment]
I found the problem: it's not possible to use these two at the same time,MSI Dragon Center，PIPSI.

**Comment by 3429mq** [comment]
![image](https://github.com/user-attachments/assets/810156d1-c256-41f0-b6bd-c5de2e18f0d5)
Turn on the "Usmikrovt de Tours Apihugin" option, which can be used at the same time
