### ISSUE TITLE
Issue addresing that the cheat doesn't work in the newest version

### ISSUE THREAD

**Issue by J1xes** [Z4ee/Pipsi-ZZZ-Releases#18]
i don't know what happen since 2 days ago i used the 0.1.4 version it worked so good that i could do reroll in a very short amount of time but the next day when i used the the ver 0.1.4 it says already terminated even when the game haven't started yet. And then i checked this github site to see if there's a new update and i downloaded the 0.1.6 one and it says its terminated before the window even started again. And today as for 0.1.7 i thought it is already been fixed but for this 0.1.7 it doesn't says that it terminated but it says this instead "Invalid checksum for 'C:\HoYoPlay\games\ZenlessZoneZero Game\UnityPlayer.dll'. Expected 0x52CBF1A, got 0x52FBF36.
Press any key to continue . . ." i don't know what's that and i hope u can explain what is happening or even better that if u can patch the cheat to the next one so this problem would be fixed. Anyways thanks :)

**Comment by akiet25** [comment]
just wait a lastest version cuz a bit update launcher in morning

**Comment by J1xes** [comment]
damn hoyo be patching their game like crazy quick

**Comment by J1xes** [comment]
> just wait a lastest version cuz a bit update launcher in morning

damn hoyo be patchin their game real crazy quick

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.1.9

**Comment by J1xes** [comment]
> https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.1.9

thanks man ur the GOAT!!!

**Comment by J1xes** [comment]
thanks man ur the GOAT fr

**Comment by Yklimx** [comment]
Expected 0x52CBF1A/0x52FBF36, got 0x531BB49 , Do you need to wait for updates?

**Comment by Maxbyte07** [comment]
\GameAssembly.dll' . Expected 0x165D4073, got 0x16616FAF. It's new error i guess?

**Comment by Z4ee** [comment]
> Expected 0x52CBF1A/0x52FBF36, got 0x531BB49 , Do you need to wait for updates?

https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.2.0

**Comment by StarlightGlimmer114** [comment]
Version 0.2.0 still doesn't work,Expected Ox165D4073, got Ox165B96D7

**Comment by Z4ee** [comment]
> Version 0.2.0 still doesn't work,Expected Ox165D4073, got Ox165B96D7

https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.2.1
