### ISSUE TITLE
noclip issue

### ISSUE THREAD

**Issue by smayouo** [Z4ee/Pipsi-ZZZ-Releases#20]
When I use the noclip , the character automatically flies upwards, even though I'm not pressing the spacebar.
*I restart my computer and fix it
Then the setting config some time will miss.

**Comment by smayouo** [comment]
And sometime inject doesn't work.
ver. 0.1.9

**Comment by Z4ee** [comment]
> When I use the noclip , the character automatically flies upwards, even though I'm not pressing the spacebar. *I restart my computer and fix it Then the setting config some time will miss.

just when this happens press the spacebar once

**Comment by smayouo** [comment]
> > 當我使用 noclip 時，即使我沒有按空白鍵，角色也會自動向上飛行。 *我重新啟動電腦並修復它然後設定配置有時會丟失。
> 
> 就在發生這種情況時按一次空白鍵

Got it,thx
