### ISSUE TITLE
Latest Windows 11 IoT LTSC injection issue

### ISSUE THREAD

**Issue by ramoops** [Z4ee/Pipsi-ZZZ-Releases#21]
Hi, uhh got an issue where Cheat.dll just freezes game after injecting it (tried via different injector with loaded bypass.dll, didn't work either; empty kiero dx11 base injects successfully and performs okay, but not pipsi)
vid: https://streamable.com/mpx1ir
Just tested and works on 10 ltsc iot fine, and I don't know what to provide also sooo yeah

**Comment by CoolBreeze0** [comment]
一样的问题到现在也没有解决呢也不知道有什么解决办法不过我玩的是国服

**Comment by klm99tt** [comment]
For it to work you must disable Windows Defender and run the trick with 3dmigoto

**Comment by ramoops** [comment]
> For it to work you must disable Windows Defender and run the trick with 3dmigoto

I have windows defender disabled always, 3dmigoto works fine just as empty dll, after some research, I have a theory that it doesnt work because of vmp (or other obf) in pipsi dll. By the way, I saw people running on 11 pro and it was fine for them

**Comment by klm99tt** [comment]
> > Para que funcione debes desactivar Windows Defender y ejecutar el truco con 3dmigoto
> 
> Tengo Windows Defender siempre desactivado, 3dmigoto funciona bien como una dll vacía, después de investigar un poco, tengo la teoría de que no funciona debido a VMP (u otro OBF) en la dll de Pipsi. Por cierto, vi gente que usaba 11 Pro y les funcionaba bien.

What I mean is to inject the trick when running 3dmigoto observe
![Captura](https://github.com/user-attachments/assets/28408cba-d866-40d1-a93a-c25dbe5e38d5)

**Comment by ramoops** [comment]
hm, will try later

**Comment by ramoops** [comment]
> > > Para que funcione debes desactivar Windows Defender y ejecutar el truco con 3dmigoto
> > 
> > 
> > Tengo Windows Defender siempre desactivado, 3dmigoto funciona bien como una dll vacía, después de investigar un poco, tengo la teoría de que no funciona debido a VMP (u otro OBF) en la dll de Pipsi. Por cierto, vi gente que usaba 11 Pro y les funcionaba bien.
> 
> What I mean is to inject the trick when running 3dmigoto observe ![Captura](https://private-user-images.githubusercontent.com/161899570/362572365-28408cba-d866-40d1-a93a-c25dbe5e38d5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwODk1NjQsIm5iZiI6MTcyNTA4OTI2NCwicGF0aCI6Ii8xNjE4OTk1NzAvMzYyNTcyMzY1LTI4NDA4Y2JhLWQ4NjYtNDBkMS1hOTNhLWMyNWRiZTVlMzhkNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwNzI3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDVmYjIxYmE1YWVhYzE4NTllZDgyZjUwYjEzZDdjN2RhZGQ0NjJjMmRjMGE5MDY0Y2I2NmM1NGQ0YjdlMGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WnSHum7xhrtAWpkayuNYcU6G1-G_L6GgslLWAVDgOEM)

https://streamable.com/ww9b3t, doesn't work

**Comment by klm99tt** [comment]
Fullscreen gameplay with cheat causes forced reboot. To fix it you need to play in windowed mode, that's what works for me with the trick activated. I have a GTX1070 8GB VRAM graphics card.

**Comment by klm99tt** [comment]
put the game in windowed mode and place the Pipsi-ZZZ-0.2.4 in a folder outside of 3dmigoto

**Comment by klm99tt** [comment]
then it's still up to date, try adding `delay=60000` in settings.ini
![Captura](https://github.com/user-attachments/assets/767f1b1c-d321-4283-8b2b-8117cbd29eff)

**Comment by klm99tt** [comment]
uninstall hoyoverse launcher

**Comment by ramoops** [comment]
I'm not using hoyo's launcher, will try now with delay and windowed mode (btw I have borderless window and it worked fine on win10)

**Comment by klm99tt** [comment]
> I'm not using hoyo's launcher, will try now with delay and windowed mode (btw I have borderless window and it worked fine on win10)

Otherwise it will not let you activate the cheat, which is why the game freezes because hoyoverse activates HoYoKProtect.sys again.

**Comment by ramoops** [comment]
still freezes

**Comment by klm99tt** [comment]
No friend, I explained to yThe hoyoverse even if you have not started it interacts with the Zenless Zone Zero gameou that the game freezes when running that in full screen..

**Comment by ramoops** [comment]
I just tried in windowed mode, it still freezes, I think it's issue with win11 + obfuscation in dll

**Comment by klm99tt** [comment]
> I just tried in windowed mode, it still freezes, I think it's issue with win11 + obfuscation in dll

Note that you must run 3dmmigoto or the trick as administrator, otherwise it won't work.

**Comment by ramoops** [comment]
I did

**Comment by klm99tt** [comment]
Well try to install Windows 10 Pro and see if you can do it. I use modified Windows 10 Pro.

**Comment by klm99tt** [comment]
Please note that Bypass.dll is injected after 3 attempts.

**Comment by klm99tt** [comment]
It took me 9 hours to understand how this works

**Comment by ramoops** [comment]
> Well try to install Windows 10 Pro and see if you can do it. I use modified Windows 10 Pro.

on windows 10 everything is FINE, but not on 11 iot ltsc

**Comment by klm99tt** [comment]
I solved that problem you have by uninstalling hoyoverse launcher

**Comment by klm99tt** [comment]
> > Well try to install Windows 10 Pro and see if you can do it. I use modified Windows 10 Pro.
> 
> on windows 10 everything is FINE, but not on 11 iot ltsc
then the problem is that windows

**Comment by ramoops** [comment]
> I solved that problem you have by uninstalling hoyoverse launcher

I dont have it installed

**Comment by CoolBreeze0** [comment]
系统的镜像https://www.123pan.com/s/LvuuVv-sJKCA
