### ISSUE TITLE
BIG PROBLEM if using this

### ISSUE THREAD

**Issue by havok585** [Z4ee/Pipsi-ZZZ-Releases#4]
So after double testing, WITH and without this loader, the INGAME FPS tanks from 200 (the usual i have) to 60 and sometimes even 40 (stutters) ! 

What the hell is this loader doing that it takes so much of my GPU power?

Also i did not use any SINGLE function of the cheese, just to see if something changes!
nope, framerate never went above 60.

**Comment by Z4ee** [comment]
> So after double testing, WITH and without this loader, the INGAME FPS tanks from 200 (the usual i have) to 60 and sometimes even 40 (stutters) !
> 
> What the hell is this loader doing that it takes so much of my GPU power?
> 
> Also i did not use any SINGLE function of the cheese, just to see if something changes! nope, framerate never went above 60.

look in the task manager which gpu is being loaded
maybe the game is not using your main gpu but using the built-in one

**Comment by SheJinping** [comment]
ive noticed the same thing. when i launch the game from hoyoplay the fps is stable. thank you

**Comment by havok585** [comment]
> > So after double testing, WITH and without this loader, the INGAME FPS tanks from 200 (the usual i have) to 60 and sometimes even 40 (stutters) !
> > What the hell is this loader doing that it takes so much of my GPU power?
> > Also i did not use any SINGLE function of the cheese, just to see if something changes! nope, framerate never went above 60.
> 
> look in the task manager which gpu is being loaded maybe the game is not using your main gpu but using the built-in one

Why would i have 200 fps then being restricted to 60 ? does not make sense, but just to take that variable out, i only have one GPU.

**Comment by Summeiru** [comment]
> > > So after double testing, WITH and without this loader, the INGAME FPS tanks from 200 (the usual i have) to 60 and sometimes even 40 (stutters) !
> > > What the hell is this loader doing that it takes so much of my GPU power?
> > > Also i did not use any SINGLE function of the cheese, just to see if something changes! nope, framerate never went above 60.
> > 
> > 
> > look in the task manager which gpu is being loaded maybe the game is not using your main gpu but using the built-in one
> 
> Why would i have 200 fps then being restricted to 60 ? does not make sense, but just to take that variable out, i only have one GPU.
> 
> LE: I downloaded the new update you just posted, the issue still remains.

Try to unlock your FPS in loader, i think fps unlocker locks your fps to 60 until you set it to the value you want
P.S. sorry if my english is bad

**Comment by havok585** [comment]
@Summeiru oh, i figured that out already, the cheese has it's own FPS unlocker, but somehow it conflicts with the GAME owns unlimited FPS option. ANYWAYS

the cheese is not working atm, it crashes the game the second you press login  in the world.

**Comment by havok585** [comment]
latest update fixed almost everything, you still have to use this tool own fps unlocker function if u want to go over the FPS cap, since the ingame is in conflict with this one.
