### ISSUE TITLE
Не работает GUI в игре

### ISSUE THREAD

**Issue by nonyyyr** [Z4ee/Pipsi-ZZZ-Releases#40]
**На прожатие Insert реагирует только курсор**(становится курсором винды), при этом действия блокируются, можно ходить и прожимать горячие клавиши, но при этом курсором нажать ни на что нельзя. От чего вывод: открываться окно - **открывается, но не показывается.**
рыская по интернету не нашел ничего по этому вопросу

**Comment by Z4ee** [comment]
отключи приложения с оверлеями (MSI Afterburner и т. д.).

**Comment by nonyyyr** [comment]
Спасибо, помогло
