### ISSUE TITLE
1.4中文版出现问题

### ISSUE THREAD

**Issue by HOJOEM0912** [Z4ee/Pipsi-ZZZ-Releases#56]
![image](https://github.com/user-attachments/assets/252d89b8-c6a9-40ec-87b5-22f52655c906)

**Comment by nakiriayame0** [comment]
same problem bro

**Comment by Szechuan416** [comment]
same problem bro

**Comment by damahatuoniao** [comment]
same problem dad

**Comment by xcdlh** [comment]
same problem

**Comment by qinqinwoba** [comment]
same problem  bro

**Comment by starsdream666** [comment]
由于游戏小更新导致的错误，可以下载这个替换文件来修复，只要把里面的文件拖入到游戏根目录就可以了，注意备份原文件！注意备份原文件！注意备份原文件！

123云盘（仅包含中文版）
[https://www.123865.com/s/bzakjv-Dqk0d](url)

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.3.4
