### ISSUE TITLE
1.4中文出现问题

### ISSUE THREAD

**Issue by CoolBreeze0** [Z4ee/Pipsi-ZZZ-Releases#57]
No executable specified in the configuration. Opening file selection dialog...
Invalid checksum for 'E:\ZenlessZoneZero Game\GameAssembly.dll'.
Expected 0x18D573E7 'HOYOPLAY 1.4.0 CN', got 0x18D1E368 'UNKNOWN'.
Press any key to continue . . .

**Comment by qinqinwoba** [comment]
Yes, I also have the same problem.

**Comment by SiYueChuXue** [comment]
I have the same problem.

**Comment by Allenmnum** [comment]
The Chinese version is not available

**Comment by starsdream666** [comment]
由于游戏小更新导致的错误，可以下载这个替换文件来修复，只要把里面的文件拖入到游戏根目录就可以了，注意备份原文件！注意备份原文件！注意备份原文件！

123云盘（仅包含中文版）
[https://www.123865.com/s/bzakjv-Dqk0d](url)

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.3.4
