### ISSUE TITLE
Chinese version can't use

### ISSUE THREAD

**Issue by woshiniba-debug** [Z4ee/Pipsi-ZZZ-Releases#59]

**Comment by starsdream666** [comment]
由于游戏小更新导致的错误，可以下载这个替换文件来修复，只要把里面的文件拖入到游戏根目录就可以了，注意备份原文件！注意备份原文件！注意备份原文件！

123云盘（仅包含中文版）
[https://www.123865.com/s/bzakjv-Dqk0d](url)
