### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Valkorion7** [Z4ee/Pipsi-ZZZ-Releases#6]
Hi , after the update the game always crash

**Comment by VeoTK** [comment]
v0.1.2 connecting to game server crash, v0.1.3 same

**Comment by jschua** [comment]
Same, its crashing at "logging in" part specifically so maybe they did something in the update.

**Comment by havok585** [comment]
I dont have this issue, both 0.1.2 and the latest.
make sure your AV does not flag the files inside the archive, you might be running different versions of the loader and cheese and that could have issues, just guessing.

**Comment by kevin07429** [comment]
Same, use 0.1.2 or the latest , still crash connecting to game server

**Comment by IILumex** [comment]
I can confirm that today the game started crashing.

**Comment by Chamsouu** [comment]
Yep crashes on launch

**Comment by havok585** [comment]
After further testing, the game crashes on me too, the only variable that i did not use before the crashes was the FPS unlocker, now after i did use that function, the game will have FPS unlocked (at the specified frame rate  the trainer was set) without even having the function ON.

**Comment by kevin07429** [comment]
> 经过进一步测试，游戏也崩溃了，我在崩溃前唯一没有使用的变量是 FPS 解锁器，现在在我使用该功能后，游戏将解锁 FPS（在训练师设置的指定帧速率下）甚至没有打开该功能。
> 
> LE：我回到了 0.1.2，现在连那个都行不通了，很奇怪，因为它以前行过。当您尝试登录世界时，游戏会崩溃。

yep , i run 0.1.2 and the latest on my other computer , it didn't crash but when i stop the game ,restart it ,crash happened

**Comment by kevin07429** [comment]
> > 经过进一步测试，游戏也崩溃了，我在崩溃前唯一没有使用的变量是 FPS 解锁器，现在在我使用该功能后，游戏将解锁 FPS（在训练师设置的指定帧速率下）甚至没有打开该功能。
> > LE：我回到了 0.1.2，现在连那个都行不通了，很奇怪，因为它以前行过。当您尝试登录世界时，游戏会崩溃。
> 
> 是的，我在另一台计算机上运行 0.1.2 和最新版本，它没有崩溃，但是当我停止游戏，重新启动它时，崩溃发生了

I wonder if the program will write a file to the game after it runs, but this has no effect on the first time you enter the game, and the second time you enter the game, an error will occur, causing a crash

**Comment by nyjam** [comment]
ZZZ had a small update and now the program is detected by the game. I tried every version and uninstall / reinstall the game but it's still detected no matter what.

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.1.5
