### ISSUE TITLE
Mine works fine ¯_(ツ)_/¯

### ISSUE THREAD

**Issue by Ryuu43** [Z4ee/Pipsi-ZZZ-Releases#8]
![image](https://github.com/Z4ee/Pipsi-ZZZ-Releases/assets/72246166/4c96f310-ef62-410c-b45e-689ca2865a55)

**Comment by ahykono** [comment]
Does that mean ZZZ works for you rn? Have you tried it after updating the game from Hoyo

**Comment by Ryuu43** [comment]
> Does that mean Pipsi works for you? Is your game updated

yes, my game and cheese are updated

**Comment by havok585** [comment]
why why would i play in windowed mode ? it doesnt have borderless window mode like others, so it looks very bad.
also the cheese worked in fullscreen with no problems. that's not the issue.

**Comment by Ryuu43** [comment]
I play windowed mode all the time so idk ¯\_(ツ)_/¯

**Comment by havok585** [comment]
the game got an update yesterday, the loader cant even load the code so what are we talking about ? it's outdated already.

**Comment by Ryuu43** [comment]
What do you mean "loader can't even load" I'm using it now, no problem
![image](https://github.com/Z4ee/Pipsi-ZZZ-Releases/assets/72246166/d9066080-d546-4eae-b513-c9641622f639)

**Comment by 455793** [comment]
ok good for you but why open this issue ? can u just comment in this instead ? #6
