### ISSUE TITLE
How to solve this issue

### ISSUE THREAD

**Issue by smayouo** [Z4ee/Pipsi-ZZZ-Releases#9]
'E:\ZenlessZoneZero Game\GameAssembly.dll'. Expected 0x16616FAF, got 0x165D4073.

**Comment by ahykono** [comment]
It means that the game updated and the hashes changed, cus Pipsi did not get an update yet (Let z4ee sleep). 
The old hashes do not match with the new ones, it's a check to prevent using it and risk getting banned

Just be patient until an updated version releases :)

**Comment by smayouo** [comment]
Got it,
thx

**Comment by AKiSA07** [comment]
Hoyoplay launcher update may cause this error, I used pipsi to launch the game and update it without any problems.

**Comment by zzz-commit** [comment]
It was a hoyoplay error, so I re-installed it, but it didn't work

**Comment by havok585** [comment]
the game has a different version simple (the cheese tries to bypass the same signature but it was changed).

**Comment by Tsukatsou** [comment]
hi !
Can someone send me the Z4ee discord ?
Thanks =)

**Comment by ahykono** [comment]
> hi !
> Can someone send me the Z4ee discord ?
> Thanks =)

The vanity url is "pipsi"

**Comment by Tsukatsou** [comment]
Thanks I'd founded <3

**Comment by Z4ee** [comment]
https://github.com/Z4ee/Pipsi-ZZZ-Releases/releases/tag/0.1.5
